### ISSUE TITLE
Incorrect rewrite target generated for ingress-nginx when specifying path.base

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk#202]
When I add the following extension to my openapi definition:

```yaml
x-kusk:
  path:
    base: /api
```

in combination with an operation-level disable:

```yaml
  /pet/findByStatus:
    x-kusk:
      disabled: true
```

the generated ingresses for each operation contain mismatching `/path` and `nginx.ingress.kubernetes.io/rewrite-target` properties - the later is missing the path.base extension:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /store/inventory
  creationTimestamp: null
  name: petstore-store-inventory
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: petstore
            port:
              number: 8001
        path: /api/store/inventory
        pathType: Exact
status:
  loadBalancer: {}

```
