### ISSUE TITLE
Support Swagger 2 basePath property

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kusk#203]
When kusk generates operation-specific ingresses from a swagger2 specification, the (optional) basePath in that definition gets lost. For example if my Swagger2 definition contains

```yaml
basePath: "/api"
```

and an operation-level override for some operation: 

```yaml
    x-kusk:
      disabled: true
```

the generated ingresses are missing the leading "/api" path segment - which I have to add manually; 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /pet
  creationTimestamp: null
  name: petstore-pet
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: petstore
            port:
              number: 8001
        path: /pet
        pathType: Exact
status:
  loadBalancer: {}
```
